config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users

  match '/faq',        to: 'static_pages#faq', :via => [:get]
  get   '/rules'       =>  'static_pages#rules'  
  root                 to: 'static_pages#home'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'new'  => 'boards#new'
  post    'boards'  => 'boards#create'

  resources :account_activations, only: [:edit]
  get 'boards' => "boards#index"
  delete 'nuke/:board_address' => 'boards#destroy', as: "nuke"
  post   'create_ip_status' => 'ip_statuses#create', as: 'create_ip_status'
  delete 'destroy_msg' => 'messages#destroy', as: "destroy_msg"
  get 'topics' => 'topics#index'  
  
  
  resources :boards, param: :address, constraints: {address: /[a-z0-9]+/}, only: [:show], path: '/', as: "board" do
    post 'messages' => 'messages#create'
    post 'assign'   => 'user_board_relationships#create'
    delete 'unassign/:id' => 'user_board_relationships#destroy', as: 'unassign'
    get 'edit' => 'boards#edit', as: "edit"                #board_edit_path
    get 'mod'  => 'boards#mod', as:  "mod"
    delete 'mod' => 'ip_statuses#destroy', as: 'destroy_ip_status'
    patch 'update' => 'boards#update', as: 'update'
    get 'users' => 'boards#users'
    resources :topics, only: [:show], path: '/', as: "topic"
    post '' => 'messages#create', as: ''       #for smooth posts=>topic #board_path
    post ':id' => 'messages#create', as: 'msg' #for smooth replies      #board_msg_path
  end

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'static_pages#error_404', :via => [:get]
  end
  

end

app/views/shared/_board_info.html.erb
<nav class="nav nav-justified">
  <ul class="list-inline">
    <% if is_in_board? && 
          admin_or_board_owner?(@board) %>
      <li><%= link_to (t :edit_board), board_edit_path(@board) %></li>
    <% end %>
    <% if mod?(@board) %>
      <li><%= link_to (t :mod_board), board_mod_path(@board) %></li>
    <% end %>
  </ul>
</nav>
<h1><%= @board.title %></h1>
<h3><%= @board.description %></h3>

app/views/shared/_error_messages.html.erb
<div id="error_messages">
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
</div>

app/views/shared/_message_form.html.erb
<legend><%= t :write_something %></legend>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= bootstrap_form_for(message) do |f| %>
      <%= f.text_area :content, label: (t :text) %>
      <% if admin_or_board_owner?(@board) %>
        <%= f.form_group :options do %>
          <%= f.check_box :sticky, label: (t :sticky), value: true, inline: true %>
          <%= f.check_box :open, label: (t :open), value: true, checked: true, inline: true %>
        <% end %>
      <% end %>
      <% if params[:controller] == "boards" %>
        <%= f.hidden_field :board_id, value: @board.id %>
      <% elsif params[:controller] == "topics" %>
        <%= f.hidden_field :topic_id, value: @topic.id %>
      <% end %>

      <%= f.fields_for :uploads do |upload| %>
        <%= upload.file_field :file %>
      <% end %>
      <%= f.submit (t :create), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_msg_errors.html.erb
<% if msg.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(msg.errors.count, "error") %>.
    </div>
    <ul>
    <% msg.errors.messages.each do |i| %>
      <li><%= i[1][0] %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_op.html.erb
<div id="<%= topic.messages[0].id %>">
<div class="pull-left">
<%= render partial: 'shared/upload', collection: topic.messages[0].uploads, as: :upload %>
</div>
<div class="media-body">
<%= raw(topic.messages[0].processed_content) %>
</div>

<!-- Footer -->
<ul class="list-inline list-unstyled post-description" style="clear:both;">
            <li><%= topic.id %>-<%= link_to topic.messages[0].id, "##{topic.messages[0].id}", onclick: "quote('>>#{topic.messages[0].id}')" %></li>
            <li>|</li>
            
            <% if mod?(topic.board) %>
              <li class="ip_digest"><%= topic.messages[0].ip_digest %></li>
              <li>|</li>            
            <% end %>            
            
            <li class="public_name">
              <%= topic.messages[0].public_name %>
            </li>
            <li>|</li>
  			    <li><span><i class="glyphicon glyphicon-calendar"></i> <%= l topic.created_at %> </span></li>
            <li>|</li>



            <span><span class="glyphicon glyphicon-comment"></span>
                  <% if params[:controller] == "topics" %>
                    <%= ("#{topic.messages.count-1} " + Russian.p(topic.messages.count-1, "ответ", "ответа", "ответов")) %>
                  <% else %>
                    <%= link_to "#{topic.messages.count-1} " + Russian.p(topic.messages.count-1, "ответ", "ответа", "ответов"), 
                                   board_topic_path(topic.board, topic) %>
                  <% end %>
            </span>
</ul>
<!-- Footer end -->
</div>

app/views/shared/_reply.html.erb
<div class="well reply col-md-offset-1" id="<%= reply.id %>">

<div class="pull-left">
  <%= render partial: 'shared/upload', collection: reply.uploads, as: :upload %>
</div>
<div class="media-body">
  <%= raw(reply.processed_content) %>
</div> 
  <!-- Footer -->
  <ul class="list-inline list-unstyled post-description">
            <li>
              <%= link_to reply.id, "##{reply.id}", onclick: "quote('>>#{reply.id}')" %>   
            </li>     
            <li>|</li>  
            
            <% if mod?(reply.topic.board) %>
              <li class="ip_digest"><%= reply.ip_digest %></li>
              <li>|</li>            
            <% end %>    
          
            <li class="public_name">
              <%= reply.public_name %>
            </li>
            <li>|</li>
  			    <li><span><i class="glyphicon glyphicon-calendar"></i> <%= l reply.created_at %> </span></li>
  </ul>
  <!-- footer end -->

</div>

app/views/shared/_reply_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= bootstrap_form_for(msg, url: board_messages_path(@board), html: {method: "post"}, remote: true) do |f| %>
      <%= f.text_area :content, label: (t :text) %>
      <%= f.hidden_field :topic_id, value: @topic.id %>
      <%= f.simple_captcha :label => "Enter symbols.." %>
      <%= f.fields_for :uploads do |upload| %>
        <%= upload.file_field :file %>
      <% end %>
      <%= f.submit (t :create), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_upload.html.erb
<% if upload.file.file? %>
  <div class="img-thumbnail">
    <%= link_to(image_tag(upload.file.url(:thumb), 
                          class: "media object",
                          onclick: "switch_img(event, this, '#{upload.file.url(:original)}')"),
                upload.file.url(:original),
                target: "_blank") %>
    <br/>
    <%= upload.file.content_type.gsub('image/', '') %>, <%= upload.file.size/1000 %>kb, <%= link_to "link", upload.file.url, target: "_blank" %>
  </div>
<% end %>