config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users

  match '/faq',        to: 'static_pages#faq', :via => [:get]
  get   '/rules'       =>  'static_pages#rules'  
  root                 to: 'static_pages#home'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'new'  => 'boards#new'
  post    'boards'  => 'boards#create'

  resources :account_activations, only: [:edit]
  get 'boards' => "boards#index"
  delete 'nuke/:board_address' => 'boards#destroy', as: "nuke"
  post   'create_ip_status' => 'ip_statuses#create', as: 'create_ip_status'
  delete 'destroy_msg' => 'messages#destroy', as: "destroy_msg"
  get 'topics' => 'topics#index'  
  
  
  resources :boards, param: :address, constraints: {address: /[a-z0-9]+/}, only: [:show], path: '/', as: "board" do
    post 'messages' => 'messages#create'
    post 'assign'   => 'user_board_relationships#create'
    delete 'unassign/:id' => 'user_board_relationships#destroy', as: 'unassign'
    get 'edit' => 'boards#edit', as: "edit"                #board_edit_path
    get 'mod'  => 'boards#mod', as:  "mod"
    delete 'mod' => 'ip_statuses#destroy', as: 'destroy_ip_status'
    patch 'update' => 'boards#update', as: 'update'
    get 'users' => 'boards#users'
    resources :topics, only: [:show], path: '/', as: "topic"
    post '' => 'messages#create', as: ''       #for smooth posts=>topic #board_path
    post ':id' => 'messages#create', as: 'msg' #for smooth replies      #board_msg_path
  end

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'static_pages#error_404', :via => [:get]
  end
  

end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  address     :string(255)
#  description :string(255)      default("")
#  created_at  :datetime
#  updated_at  :datetime
#

class Board < ActiveRecord::Base
  has_many :user_board_relationships, class_name:  "UserBoardRelationship",
                                      foreign_key: "board_id",
                                      dependent:   :destroy
  has_many :users, through: :user_board_relationships, source: :user
  has_many :topics, :dependent => :destroy
  has_many :messages, :dependent => :destroy
  has_many :ip_statuses
  #after_create :init_assign_owner
  apply_simple_captcha
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }, uniqueness: { case_sensitive: false }
  validates :description, length: { maximum: 220 }
  VALID_ADDRESS_REGEXP = /\A[a-zA-Z]\w+\z/i
  validates :address, presence: true, 
                      length: { maximum: 20 },
                      format: { with: VALID_ADDRESS_REGEXP },
                      uniqueness: { case_sensitive: true }
  before_save :downcase_stuff

=begin
  def init_assign_owner
    ##If Board is created from User, make him owner
    #if self.users.any? 
      to_change = self.user_board_relationships.first
      to_change.role = "owner"
      to_change.save!
    #end
  end
=end

  def assign_user(user, role="mod")
    if user.nil?
      self.errors.add(:user_board_relationships, "There is no user with such id")
    else
      ubr = self.user_board_relationships.create!(user_id: user.id, role: role)
    end
  end

  def to_param
    address.parameterize
  end 

  def owner
    ubr = self.user_board_relationships.where(role: 'owner').first
    if !ubr.nil?
      return User.find(ubr.user_id)
    else
      return nil
    end
    #This opens undesirable possibility of having multiple owners
  end

  private
  
    def downcase_stuff
      self.address = address.downcase
    end 
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
before_action :logged_in_user, only: [:create, :new]
before_action :admin_user, only: [:destroy]

  def create
    @board = current_user.boards.new(board_params)
    @user = current_user
    if @board.valid?
      @board.save
      UserBoardRelationship.create!(board_id: @board.id, user_id: @user.id, role: 'owner')
      redirect_to @board
    else
      render 'new'
      flash[:error] = "captcha"
    end
  end

  def destroy
    @board = Board.find_by_address(params[:board_address])
    @board.delete
    flash[:success] = "Board destroyed"
    redirect_to boards_path
  end

  def edit
    @board = Board.find_by_address(params[:board_address])
  end

  def index
    add_breadcrumb I18n.t('boards'), "boards"
    @boards = Board.paginate(page: params[:page])
  end
  
  def mod
    @board = Board.find_by_address(params[:board_address])
    add_breadcrumb @board.title, @board
    add_breadcrumb 'mod', 'mod', class: 'active'
    if mod?(@board)
      #render forms
      @ip_status = IpStatus.new
      @ip_statuses = @board.ip_statuses
    else 
      redirect_to root_url
    end
  end

  def new
    add_breadcrumb I18n.t('new_board'), 'new'
    @board = Board.new
  end

  def show
    @board = Board.find_by_address(params[:address])
    add_breadcrumb I18n.t('boards'), boards_path
    add_breadcrumb @board.title, @board.address, class: 'active'
    @topics = @board.topics.all.paginate(page: params[:page])
    @message = Message.new             #Message form
    6.times { @message.uploads.build }
  end

  def update
    @board = Board.find_by_address(params[:board_address])  
    if @board.update_attributes(board_edit_params)
      flash[:success] = "Сохранено"
      redirect_to @board
    else
      render 'edit'
    end
  end
  
  def users
    @board = Board.find_by_address(params[:board_address])  
    add_breadcrumb I18n.t('boards'), boards_path
    add_breadcrumb @board.title, @board.address
    add_breadcrumb I18n.t('users'), 'users', class: 'active'
    @users = @board.users.all.paginate(page: params[:page])
  end

  private

    def admin_user
      redirect_to root_path unless current_user && current_user.admin?
    end

    def board_params
      params.require(:board).permit(:title, :address, :description)
    end

    def board_edit_params
      params.require(:board).permit(:title, :description)    
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please lög in."
        redirect_to login_url
      end
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
  def is_in_board?
    !params[:address].nil? or !params[:board_address].nil?
  end

  def board_sym
    if params[:address]
      :address
    elsif params[:board_address]
      :board_address
    else
      nil
    end
  end
  
  def ban
    ip = create_ip_digest(request.remote_ip)
    if board_sym
      @board = Board.find_by_address(board_sym)
      IpStatus.where('expires_at > ?', Time.now).find_by_ip_digest(ip)
    end
  end
end

app/views/boards/_board.html.erb
<tr>
  <td><%= link_to board.title, board_path(board) %></td>
  <td><%= board.messages.where("created_at > ?", 1.days.ago).count %></td>
  <td><%= board.messages.where("created_at > ?", 7.days.ago).count %></td>
  <td><%= board.messages.count %></td>
  <td><%= !board.owner.nil? ? link_to(board.owner.name, board.owner) : nil %></td>
  <% if admin_or_board_owner?(board) %>
    <td><%= link_to (t :destroy_board), nuke_path(board), method: "delete", data: { confirm: "You sure?" } %></td>
  <% end %>
</tr>

app/views/boards/_error_messages.html.erb
<% if @board.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@board.errors.count, "error") %>.
    </div>
    <ul>
    <% @board.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/boards/_user.html.erb
<tr>
  <td><%= link_to user.name, user %></td>
     <% if logged_in? && admin_or_board_owner?(@board) %>
  <td> 
      | <%= link_to (t :unassign), board_unassign_path(@board, user), method: :delete,
                                   data: { confirm: "You sure?" } %>
    
  </td>
    <% end %>
</tr>

app/views/boards/edit.html.erb
<% provide(:title, (t :edit_board)) %>
<legend><%= (t :edit_board) + " \"#{@board.title}\"" %></legend>

<% if admin_or_board_owner?(@board) %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= bootstrap_form_for(@board, url: board_update_path(@board), html: {method: "patch"}) do |f| %>
      <%= render 'error_messages' %>
      <%= f.text_field :title, label: (t :title) %>
      <%= f.text_area :description, label: (t :description) %>

      <%= f.submit (t :create), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
<% end %>

app/views/boards/index.html.erb
<%= link_to (t :create), new_path, class: "btn btn-primary btn-lg" %>

<br/>

<%= will_paginate %>

<table class="table table-hover">
  <tr>
  <th><%= t :title %></td>
  <th>24 <span class="glyphicon glyphicon-time"></span></th>
  <th>7 <span class="glyphicon glyphicon-calendar"></span></th>
  <th>Σ <span class="glyphicon glyphicon-globe"></span></th>
  <th><%= t :owner_name %></th>  
  <% if admin? %>
    <th><%= t :actions %></th> 
  <% end %>
  </tr>
  <%= render @boards %>
</table>

<%= will_paginate %>

app/views/boards/mod.html.erb
<div class="row">
  <div class="col-md-6">
    <legend>Удаление постов</legend>
    <%= form_tag(destroy_msg_path, method: "delete") do %>
      <%= label_tag(t :post_id) %>
      <%= number_field_tag(:id) %>
      <%= submit_tag(t :delete) %>
    <% end %>
  </div>
  <div class="col-md-6">
    <legend>Блокировка пользователей</legend>
    <%= bootstrap_form_for(@ip_status, url: create_ip_status_path, html: {method: "post"}, layout: :horizontal) do |f| %>
      <%= f.text_field(:ip_digest) %>
      <%= f.text_field(:reason) %>
      <%= f.text_field(:days_left) %>
      <%= f.hidden_field(:board_address, value: params[board_sym]) %>
      <%= f.submit(t :to_ban) %>
    <% end %>
  </div>
</div>

<legend>Bans</legend>
<%= create_ip_digest(request.remote_ip) %>
<table class="table table-bordered table-striped">
<tr>
<th><%= t :ip_hash %></th>
<th><%= t :reason %></th>
<th><%= t :created_at %></th>
<th><%= t :expires_at %></th>
<th><%= t :time_left %></th>
<th></th>
</tr>
<%= render @ip_statuses %>
</table>

app/views/boards/new.html.erb
<% provide(:title, (t :new_board)) %>
<legend><%= t :new_board %></legend>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= bootstrap_form_for(@board) do |f| %>
      <%= render 'error_messages' %>
      <%= f.text_field :title, label: (t :title) %>
      <%= f.text_field :address, label: (t :address) %>
      <%= f.text_area :description, label: (t :description) %>

      <%= f.submit (t :save), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/boards/show.html.erb
<%= render 'shared/board_info' %>

<% will_paginate @topics %>

<%= render @topics %>

<% will_paginate @topics %>



<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <legend><%= t :write_something %></legend>
    <%= bootstrap_form_for(@message, url: board_path(board_address: params[board_sym]), html: {method: "post"}, layout: :horizontal) do |f| %>
      <%= f.text_area :content, label: (t :text) %>
      <% if admin_or_board_owner?(@board) %>
        <%= f.form_group :options do %>
          <%= f.check_box :sticky, label: (t :sticky), value: true, inline: true %>
          <%= f.check_box :open, label: (t :open), value: true, checked: true, inline: true %>
        <% end %>
      <% end %>

      <%= f.simple_captcha :label => "Enter symbols.." %>
      <%= f.fields_for :uploads do |upload| %>
        <%= upload.file_field :file, label: (t :file) %>
      <% end %>
      <%= f.submit (t :create), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/boards/users.html.erb
<% will_paginate @users %>

<% if admin_or_board_owner?(@board) %>
    <legend><%= t :add_mod %></legend>
    <%= form_tag(board_assign_path(@board), method: "post") do %>
      <%= label_tag(t :name) %>
      <%= text_field_tag(:name) %>
      <%= submit_tag(t :name) %>
    <% end %>
<% end %>    

<table class="table table-hover">
<tr>
  <th><%= t :user %></th>
  <% if logged_in? && current_user.admin? %><th><%= t :delete %></th><% end %>

</tr>

  <%= render partial: "user", collection: @users %>

</table>

<% will_paginate @users %>