config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users

  match '/faq',        to: 'static_pages#faq', :via => [:get]
  get   '/rules'       =>  'static_pages#rules'  
  root                 to: 'static_pages#home'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'new'  => 'boards#new'
  post    'boards'  => 'boards#create'

  resources :account_activations, only: [:edit]
  get 'boards' => "boards#index"
  delete 'nuke/:board_address' => 'boards#destroy', as: "nuke"
  post   'create_ip_status' => 'ip_statuses#create', as: 'create_ip_status'
  delete 'destroy_msg' => 'messages#destroy', as: "destroy_msg"
  get 'topics' => 'topics#index'  
  
  
  resources :boards, param: :address, constraints: {address: /[a-z0-9]+/}, only: [:show], path: '/', as: "board" do
    post 'messages' => 'messages#create'
    post 'assign'   => 'user_board_relationships#create'
    delete 'unassign/:id' => 'user_board_relationships#destroy', as: 'unassign'
    get 'edit' => 'boards#edit', as: "edit"                #board_edit_path
    get 'mod'  => 'boards#mod', as:  "mod"
    delete 'mod' => 'ip_statuses#destroy', as: 'destroy_ip_status'
    patch 'update' => 'boards#update', as: 'update'
    get 'users' => 'boards#users'
    resources :topics, only: [:show], path: '/', as: "topic"
    post '' => 'messages#create', as: ''       #for smooth posts=>topic #board_path
    post ':id' => 'messages#create', as: 'msg' #for smooth replies      #board_msg_path
  end

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'static_pages#error_404', :via => [:get]
  end
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <nav class="nav nav-justified">
        <ul>
        <% Board.all[0..19].each do |x| %>
          <li class="navbar-text"><%= link_to x.address, board_path(x) %></li>
        <% end %>
        </ul>
    </nav>
        <small>
        !!!
        </small>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <%= link_to (image_tag("/logo.png", alt: "Sulfur logo", size: "35x35")), root_path, :class=>"navbar-header navbar-brand" %>

    <ul class="nav navbar-nav">
      <%= render_breadcrumbs :tag => 'li' %>
    </ul>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to (t :boards_list), boards_path %></li>
        <li><%= link_to (t :faq), faq_path  %></li>
        <% if !logged_in? %>
        <li><%= link_to (t :sign_up), signup_path %></li>
        <li><%= link_to (t :log_in), login_path %></li>
        <% else %>
              <li><%= link_to (t :profile), current_user %></li>
              <li><%= link_to (t :settings), edit_user_path(current_user) %></li>
              <li><%= link_to (t :users), users_path %></li>
              <li><%= link_to (t :log_out), logout_path, method: "delete" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script
src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults, "http://localhost:9292/faye.js" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
<div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
<%= yield %>
        <%= debug(params) if Rails.env.development? %>
        <%= session[:return_to] if Rails.env.development?  %>
    </div>

    <%= render 'layouts/footer' %>

</body>
</html>